name: hello world
on:
    push:
        branches:
            - master

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: echo "Hello World"
            - name: give the time
              run: date
            - name: print directory
              run: ls -l
