name: Deployment pipeline

on:
    push:
        branches:
            - master

jobs:
    deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with: node-version: "16"
            - name: npm install
              run: npm install
            - name: lint
              run: npm run eslint
