name: Timed health check

on:
  schedule:
    - cron: "21 * * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Timed health check
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://hidden-waters-12808.herokuapp.com/health
          max-attemps: 2
          retry-delay: 4s
